on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  bee-images:
    name: Build and publish images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Auth to Github Package Docker Registry
        if: github.ref == 'refs/heads/master' && success()
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin
      - name: Build images
        run: |
          make build
      - name: Publish if master branch
        if: github.ref == 'refs/heads/master' && success()
        run: |
          make publish
